plot_data<-read.table('household_power_consumption.txt',header=TRUE,sep=';',stringsAsFactors=FALSE)
plot_data_filtered=plot_data[plot_data$Date %in% c("1/2/2007","2/2/2007"), ]
globalActivePower<-as.numeric(plot_data_filtered$Global_active_power)
date_time<-strptime(paste(plot_data_filtered$Date,plot_data_filtered$Time,sep=" "),format = "%d/%m/%Y %H:%M:%S")
subMetering1<-as.numeric(plot_data_filtered$Sub_metering_1)
subMetering2<-as.numeric(plot_data_filtered$Sub_metering_2)
subMetering3<-as.numeric(plot_data_filtered$Sub_metering_3)
png("plot3.png",width=480,height=480)
plot(date_time,subMetering1,type="l",xlab="",ylab="Energy sub metering")
lines(date_time,subMetering2,type="l",col="red")
lines(date_time,subMetering3,type="l",col="blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=1, lwd=2.5, col=c("black", "red", "blue"))
dev.off()
